### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by petitkriket** [ppiyush13/font-face-core#1]
Currently looking for a tool generating font face declarations but there is no documentation, not even a line to begin with. It's a pity :)

**Comment by ppiyush13** [comment]
@petitkriket, sorry for that. But I have mentioned in the readme.md, most of the time you won need this package. This package is not intended to be consumed directly.

Instead you might me interested in either https://github.com/ppiyush13/font-face-browser or https://github.com/ppiyush13/font-face-node. Both these modules consumes font-face-core module. 

Also you might be interested in https://polished.js.org/docs/#fontface. Do explore this option as well.

I hope your queries are answered.

**Comment by petitkriket** [comment]
🙏  @ppiyush13 your reply is super helpful, sorry, I did not figured out that it was a core dependency, thank you for these 3 options !
